### ISSUE TITLE
Can you share your vscode launch.json?

### ISSUE THREAD

**Issue by guillermoarellano** [asemoon/nestjs-postgres-dockerized-starter#1]
Hi,

I am trying to get the vscode debugger to connect to the Docker instance of the nest.js app with no success. Can you share your launch.json file so that I can try running it in my environment?

Kind regards,
Guillermo Arellano

**Comment by asemoon** [comment]
I don't have a launch file for vs code but if you figure it out I would appreciate it if you submitted a PR
